feat(Politicians): Added cabinet view structure to politicians
OpenPromisesProject/ui pull request #258
Opened 2020-07-01 14:23 UTC by TheCornelius

feature or bug? : Feature
changes to user:
- At /politicians page, users get to see an additional section of politicians, categorized by ministries involved, contains links.

under the hood changes:
- Modified Politicians component to include cabinet view, with use of a feature flag
- Added mock_cabinet data in mock_cabinet.js
- Added links to individual politician's page

2020-07-01 14:30 UTC, TheCornelius commented
closes #257

2020-07-06 12:30 UTC, nazreen requested changes
1. create data property and init cabinet with empty object
2. create methods property and place getCabinet there
3. inside created, call this.getCabinet to set value of this.cabinet

2020-07-06 12:30 UTC, nazreen commented on src/api/mock_cabinet.js
> +// Cabinet.vue
this file should be put inside `src/mocks/mock_cabinet.js`

2020-07-06 12:30 UTC, nazreen commented on src/api/mock_cabinet.js
> +export { mock_cabinet };
export default mock_cabinet

2020-07-06 12:30 UTC, nazreen commented on src/api/mock_cabinet.js
> +export { mock_cabinet };
// e.g. of named export
<script>
export { mock_cabinet } from './mock_cabinet'
</script>

// e.g. of default export
<script>
export mock_cabinet from './mock_cabinet'
</script>

default export is more appropriate

2020-07-06 12:30 UTC, nazreen commented on src/api/index.js
> +
return mock_cabinet
...
return Promise.resolve(mock_cabinet)

2020-07-06 12:30 UTC, nazreen commented on src/views/Politicians.vue
> +    getCabinet() {
async getCabinet() {..}
..

async getCabinet() {
  this.cabinet = await getCabinet()
}

2020-07-06 12:30 UTC, nazreen commented on src/views/Politicians.vue
> +    getCabinet() {
this should be under methods

2020-07-06 13:32 UTC, nazreen requested changes
inside Politicians.vue:
- getCabinet from `src/api/index` should be imported
- methods.getCabinet should be calling that api `geCabinet`
- `mock_cabinet` should not be imported here

in summary, the mocking should be done in `src/api/index` and not in `Politicians.vue`

2020-07-16 14:47 UTC, TheCornelius commented
closes #257 #259

2020-07-16 14:59 UTC, TheCornelius commented
closes #260

2020-07-17 14:56 UTC, nazreen commented
looks good, thanks @TheCornelius !

2020-07-17 15:20 UTC, nazreen commented
@TheCornelius I made several quick changes pre-merging:

- moved CabinetView to top of page rather than after 'All Politicians'
- removed the borders (fits our current styling better), hope that's alright
- added 'All Politicians' h1 to make clear that the section below Cabinet View is all politicians

2020-07-17 15:20 UTC, merged

2020-07-19 15:57 UTC, TheCornelius commented
The new /politicians page looks pretty clean

2020-07-20 11:08 UTC, nazreen commented
@TheCornelius glad to hear that :)